
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 10 02:06:12 CST 2020
//----------------------------------------------------

package ejemplo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 3;
  public static final int POR = 4;
  public static final int EOF = 0;
  public static final int MAS = 2;
  public static final int NUMERO = 8;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int PARC = 7;
  public static final int PARA = 6;
}

