
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 04 23:24:24 CST 2020
//----------------------------------------------------

package ejemplo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PUNTO = 8;
  public static final int LS = 3;
  public static final int CP = 14;
  public static final int RM = 12;
  public static final int ERROR = 17;
  public static final int CD = 4;
  public static final int MV = 11;
  public static final int MKDIR = 10;
  public static final int ENTER = 6;
  public static final int SPACE = 5;
  public static final int PWD = 7;
  public static final int EOF = 0;
  public static final int TEXTO = 15;
  public static final int error = 1;
  public static final int DPUNTO = 2;
  public static final int RMDIR = 13;
  public static final int TOUCH = 9;
  public static final int PATH = 16;
}

